# Generated by Django 5.2 on 2025-06-06 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizDir', '0003_business_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='business',
            name='longitude',
        ),
    ]
