# Generated by Django 5.2 on 2025-06-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizDir', '0004_remove_business_latitude_remove_business_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
