# Generated by Django 5.2 on 2025-06-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizDir', '0005_businesscategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscategory',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
