# Generated by Django 5.2 on 2025-06-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizDir', '0006_remove_businesscategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
