# Generated by Django 5.2 on 2025-06-11 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizDir', '0012_businesscategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscategory',
            name='slug',
        ),
    ]
