# Generated by Django 5.2 on 2025-06-11 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizDir', '0006_alter_businesscategory_slug'),
        ('bizDir', '0012_businesscategory_slug'),
    ]

    operations = [
    ]
