# Generated by Django 5.2 on 2025-06-11 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizDir', '0013_merge_20250611_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscategory',
            name='slug',
        ),
    ]
