# Generated by Django 5.2 on 2025-06-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizDir', '0002_remove_business_zip_code_business_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('inactive', 'Inactive')], default='pending', max_length=10),
        ),
    ]
