# Generated by Django 5.2 on 2025-06-11 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizDir', '0005_businesscategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscategory',
            name='slug',
        ),
    ]
