# Generated by Django 5.2 on 2025-06-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizDir', '0009_businesscategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
